name: loading_screen
description: A Flutter plugin to easily display and dispose standard or custom loading screens anywhere in your app.
version: 1.0.1
homepage: https://github.com/JosLuna98/loading_screen.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.jostech.loading_screen
        pluginClass: LoadingScreenPlugin
      ios:
        pluginClass: LoadingScreenPlugin
